name: flutter_typeahead
version: 4.3.7

description: A highly customizable typeahead (autocomplete) text input field for Flutter
homepage: https://github.com/AbdulRahmanAlHamali/flutter_typeahead

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.19.0 <3.0.0'

